#ifndef ERROR
#define ERROR

typedef enum {SUCCESS,
    ILIGAL_LABEL_CHARACTERS,
    ILIGAL_LABEL_NAME,
    LABEL_ALREADY_EXSIST,
    COMMAND_NOT_FOUND,
    MISSING_OPERATORS,
    MISSING_COMMA,
    GARBUIGE_AT_THE_END,
    FORGOT_QUETATION,
    ILLIGAL_CHAR_IN_NUMBER,
    ENTERY_LABEL_NOT_FOUND,
    ILLIGAL_PARATMETER,
    ILLIGAL_REGISTER_NUMBER,
    ILLIGAL_REGISTER_FORMAT,
    OPERAND_LABEL_NOT_FOUND
} Exeption;

void errorHandle(char *line, Exeption exep);

#endif
